name: Build Test

on:
    push:
        branches:
            - main
        workflow_dispatch:

jobs:
    release:
        name: build
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: ["windows-latest", "ubuntu-latest", "macos-latest"]
                arch: ["x64", "arm64"]
                node: ["22"]

        env:
            NODE_OPTIONS: "--max_old_space_size=6144"

        steps:
            - name: Check out git repository
              uses: actions/checkout@v4
              with:
                  show-progress: false

            - name: Setup Node.js ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
                  cache: "npm"

            - name: Install Dependencies
              run: npm ci

            - name: Build Electron App
              run: npm run dist --arch=${{ matrix.arch }}

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.os }}
                  path: ./out/make/**/{x64,arm64}/*
